### ISSUE TITLE
Task list design (Due: Tuesday night)

### ISSUE THREAD

**Issue by chris-529** [cse110-sp24-group32/warmup-exercise#2]
Come up with a design for our task list using Figma or some other design tool of your choice:

Main tasks:
-Mobile design
-Desktop design

Needs:
-Colors and branding (team branding maybe?)
-Should have a "task container" with a few example tasks with fake content or labeled content (either is fine)
-Proper headings displayed
-Design for what it should look like when you click on a task (maybe a popdown or popup?)

As a reminder, we are planning on having our json data be in the form of:

Task object:
-Task name
-Checkbox (done or not)
-Description/task content

**Comment by Babuka6** [comment]
done
